### ISSUE TITLE
Replace phone image with a CVG

### ISSUE THREAD

**Issue by hellyworld** [Adela-H/Workout_4#2]
@Adela-H if you want you can replace the phone image to a CVG image.

Here you can find a nice tool for SVG images. Just download them as basic config. 
https://thenounproject.com/

Code location:
https://github.com/Adela-H/Workout_4/blob/c70b3861b1afb3c5570cec71332136694f8a45f3/index.html#L21

**Comment by Adela-H** [comment]
In workout_3 tema era urmatoarea: "Iconița de telefon de preferat să fie unicode symbol, nu imagine"

**Comment by hellyworld** [comment]
Perfect, it this case you can complete this issue. It's solved

**Comment by Adela-H** [comment]
Thank you!
